name: Python Code Quality and Lint
on:
  push:
    branches: [ main ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ricardochaves/python-lint@v1.3.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

